changed write and read functions to support binary data
both functions were only supporting text data and needed to be
changed to support binary data.

The issue was found while testing libgfapi-python with smallfile
(https://github.com/bengland2/smallfile).

When calling gflfs_write, ctypes has no problem converting strings
to the correct C data type, but is unable to handle bytearray:

 b = bytearray(1024)
 with vol.create(path, os.O_WRONLY | os.O_EXCL, 0644) as fd:
   fd.write(b)

It would throw this error:
exception: argument 2: <type 'exceptions.TypeError'>:
Don't know how to convert parameter 2

reference: http://docs.python.org/2/library/ctypes.html#calling-functions-continued

Change-Id: Ia2bb47343880cbf7121fed9510e4cfa085fe23bd
Signed-off-by: Thiago da Silva <thiago@redhat.com>